# Generated by Django 2.2 on 2020-07-25 16:36

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shopuser',
            managers=[
                ('objects', users.models.ShopUserManager()),
            ],
        ),
    ]
